--------------------------------------------------------
-- Add Consultation Fee to DOCTOR table if not exists
--------------------------------------------------------
ALTER TABLE "ADMIN"."DOCTOR" ADD ("CONSULTATION_FEE" NUMBER DEFAULT 0);

--------------------------------------------------------
--  DDL for Table BOOKING_PAYMENT
--------------------------------------------------------

CREATE TABLE "ADMIN"."BOOKING_PAYMENT" 
(	
    "PAYMENT_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE, 
    "PATIENT_ID" NUMBER NOT NULL ENABLE, 
    "DOCTOR_ID" NUMBER NOT NULL ENABLE, 
    "PATIENT_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
    "DOCTOR_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
    "APPOINTMENT_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
    "DOCTOR_FEE" NUMBER DEFAULT 0, 
    "HOSPITAL_FEE" NUMBER DEFAULT 500, 
    "TOTAL_AMOUNT" NUMBER DEFAULT 500, 
    "PAYMENT_STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Paid', 
    "PAYMENT_METHOD" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
    "TRANSACTION_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
) DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
NOCOMPRESS LOGGING
TABLESPACE "DATA" ;

--------------------------------------------------------
--  Constraints for Table BOOKING_PAYMENT
--------------------------------------------------------

ALTER TABLE "ADMIN"."BOOKING_PAYMENT" ADD PRIMARY KEY ("PAYMENT_ID")
USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA"  ENABLE;

--------------------------------------------------------
--  DDL for Procedure PKG_APPOINTMENT_OPS or Independent
--------------------------------------------------------
CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN"."SAVE_BOOKING_PAYMENT" (
    p_patient_id      IN NUMBER,
    p_doctor_id       IN NUMBER,
    p_patient_name    IN VARCHAR2,
    p_doctor_name     IN VARCHAR2,
    p_appointment_date IN TIMESTAMP,
    p_doctor_fee      IN NUMBER,
    p_hospital_fee    IN NUMBER,
    p_payment_method  IN VARCHAR2,
    p_payment_status  IN VARCHAR2,
    p_payment_id      OUT NUMBER
) AS
    v_total NUMBER;
BEGIN
    v_total := COALESCE(p_doctor_fee, 0) + COALESCE(p_hospital_fee, 0);

    INSERT INTO BOOKING_PAYMENT (
        PATIENT_ID, DOCTOR_ID, PATIENT_NAME, DOCTOR_NAME, 
        APPOINTMENT_DATE, DOCTOR_FEE, HOSPITAL_FEE, TOTAL_AMOUNT, 
        PAYMENT_METHOD, PAYMENT_STATUS
    ) VALUES (
        p_patient_id, p_doctor_id, p_patient_name, p_doctor_name, 
        p_appointment_date, p_doctor_fee, p_hospital_fee, v_total, 
        p_payment_method, p_payment_status
    ) RETURNING PAYMENT_ID INTO p_payment_id;
END;
/
