-- Run this in Oracle SQL Developer (connected to localdb/XEPDB1)
-- Optional cleanup: drop the table if it already exists
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE users';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
